### ISSUE TITLE
'Connection to api.dropbox.com timed out. (connect timeout=60.0)')

### ISSUE THREAD

**Issue by Sharonno** [suryabhupa/image-clustering#1]
Hi, thank you for you codes. I've tried to install clarifai and signed up.I've also installed dropbox.then I ran the main.py which threw the error:
![screenshot from 2015-10-30 11 23 09](https://cloud.githubusercontent.com/assets/9607594/10837831/10fc8ac2-7ef9-11e5-8340-d4a1df83da44.png)
I also ran the auth.py which I had no idea about 
![screenshot from 2015-10-30 11 27 16](https://cloud.githubusercontent.com/assets/9607594/10837841/35133442-7ef9-11e5-8fd5-8c70e283a49f.png)
Could you please tell me how to deal with it?thank you very much!

**Comment by suryabhupa** [comment]
Hey! Thanks so much for checking this out. We actually left out some of the code we used because we didn't want to give away our private keys, haha. 

The issues I think you're having are with authenticating with Dropbox; check out this: https://www.dropbox.com/developers/documentation/python#tutorial because you need to register your app and set up the access token.

**Comment by Sharonno** [comment]
thank you for your reply.But I seem to have trouble visiting www.dropbox unless I use other agent ...

**Comment by suryabhupa** [comment]
That's quite strange -- is it blocked on your internet or something?

**Comment by Sharonno** [comment]
yeah...so pitty

**Comment by suryabhupa** [comment]
Darn :/ Let us know if you have any other concerns though. For now, we'll close this, but will be happy to walk you or anyone else interested through the process of setting the authentication needed to run the script.
