### ISSUE TITLE
How to use these code ?

### ISSUE THREAD

**Issue by albertyou2** [suryabhupa/image-clustering#2]
@suryabhupa HI,
Good work!But there is not any instructions here.
I have no idea how to use your code .
Could you please give some help?

**Comment by suryabhupa** [comment]
Hey there! Thanks for dropping by -- unfortunately, I haven't maintained this code in a long time, and I'm not sure myself of the useability as-is. 

The code has three main dependencies -- the Clarifai API, the Dropbox API, and the scikit-learn toolkit. You'll need to get API access tokens to the first two, but honestly, I'm not sure if the endpoints are correct anymore. What is your use case?

**Comment by albertyou2** [comment]
@suryabhupa hi,thank you for your reply!

I had a try just now and found a extremely bad problem that is ： in our country using dropbox api is not allowed  and we could not reached any dropbox's HOST.
what a pity！
Is there any method to avoid to use dropbox api in your code?

PS : My case is to classify products images by Similarity by using clustering algorithm.

thank you again~~!

**Comment by suryabhupa** [comment]
If you ran the code, it won't work because I haven't put any correct access token in Dropbox. You certainly don't need Dropbox, we were just doing it in order to query images from a Dropbox folder. 

You can do without the Dropbox folder -- just pass your images through some model that reduces their dimensionality (convolutional neural networks, PCA, etc.) and feed these representations into a clustering algorithm.

**Comment by albertyou2** [comment]
@suryabhupa thank you! I will try !

**Comment by suryabhupa** [comment]
The last thing I wanted to add is that we have one part of our code that extracts topics from an image, which is another reason to use the Clarifai API -- definitely check it out, but again, it's not necessary.

**Comment by albertyou2** [comment]
@suryabhupa  ok I got it !
